# Generated by Django 5.0.1 on 2024-01-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_remove_blogs_author_alter_blogs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='description',
        ),
    ]
